language: rust
rust:
  - nightly
os: osx
env:
  - PYTHON_VERSION=3.5.6 PYTHON_NATIVE_ABI=35
  - PYTHON_VERSION=3.6.6 PYTHON_NATIVE_ABI=36
  - PYTHON_VERSION=3.7.0 PYTHON_NATIVE_ABI=37

cache: cargo
before_install:
  - rustup default nightly
  - brew update && brew upgrade pyenv
  - eval "$(pyenv init -)"
  - pyenv install $PYTHON_VERSION
  - pyenv global $PYTHON_VERSION
  - pip install --upgrade pip
  - rustup --version; cargo --version;rustc --version;python -V;pip -V;

install:
  - pip install -r requirement-dev.txt --user

script: |
  python compile.py build && \
  cp build/lib/py_sourcemap/*.so py_sourcemap/py_sourcemap.so && \
  mkdir -p natives && \
  cp py_sourcemap/py_sourcemap.so "natives/py_sourcemap.cpython-${PYTHON_NATIVE_ABI}m-x86_64-apple-darwin.so" && \
  $HOME/.local/bin/pytest

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: natives/*.so
  skip_cleanup: true
  on:
    tags: true

deploy:
  provider: script
  script: python upload-ali-oss.py natives/*.so
  skip_cleanup: true
  on:
    tags: true
