language: rust
rust:
  - nightly
os: osx
env:
  - PYTHON_VERSION=3.5.6
  - PYTHON_VERSION=3.6.6
  - PYTHON_VERSION=3.7.0

cache: cargo
before_install:
  - rustup default nightly
  - brew update && brew upgrade pyenv
  - eval "$(pyenv init -)"
  - pyenv install $PYTHON_VERSION
  - pyenv global $PYTHON_VERSION
  - pip install --upgrade pip
  - rustup --version; cargo --version;rustc --version;python -V;pip -V;

install:
  - pip install -r requirement-dev.txt --user

script: |
  python compile.py build && \
  cp build/lib/py_sourcemap/*.so py_sourcemap/py_sourcemap.so && \
  $HOME/.local/bin/nosetests

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: py_sourcemap/py_sourcemap.so
  skip_cleanup: true
  on:
    tags: true
