language: python
os: osx

env:
  - PYTHON_VERSION=3.5.6
  - PYTHON_VERSION=3.6.6
  - PYTHON_VERSION=3.7.0

cache: cargo
before_install:
  - brew update
  - brew install rust pyenv
  - rustup default nightly
  - pyenv install $PYTHON_VERSION
  - pyenv global $PYTHON_VERSION

install:
  - pip install -r requirements-dev.txt

script: |
  python compile.py build && \
  cp build/lib/py_sourcemap/*.so py_sourcemap/ && \
  nosetests

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: build/lib/py_sourcemap/*.so
  skip_cleanup: true
  on:
    tags: true
